In [ ]:
#NumPy array and basics

In [1]:
import numpy as np

### Creating array from list

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1D-Array is:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D-Array is:", arr_2d)

1D-Array is: [1 2 3 4 5]
2D-Array is: [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [9]:
py_list = [1,2,3]
print("Python list multiplication:" , py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python list multiplication:" , np_array*2)

import time 
start = time.time()
py_list =[i*2 for i in range(1000000)]
print("\n List operation time:" ,time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:" ,time.time() - start)

Python list multiplication: [1, 2, 3, 1, 2, 3]
Python list multiplication: [2 4 6]

 List operation time: 0.2819211483001709

 Numpy operation time: 0.0


### Creating array from scratch

In [18]:
zeros = np.zeros((3,4))
print("zeroes array:\n",zeros)

ones = np.ones((3,4))
print("one array: \n",ones)

full= np.full((2,3),9)
print("full array: \n",full)

random = np.random.random((3,3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)

zeroes array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[9 9 9]
 [9 9 9]]
random array: 
 [[0.97547331 0.50138676 0.7809663 ]
 [0.33876365 0.53471461 0.72672442]
 [0.43146855 0.4164298  0.06184221]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector,Matrix and Tensor

In [21]:
vector = np.array([1,2,3])
print("Vector:\n",vector)

matrix = np.array([[1,2,3],
                 [4,5,6]])
print("Marix:\n",matrix)

tensor = np.array( [[[1,2],[3,4]], 
                   [[5,6],[7,8]]] )
print("Tensor:\n",tensor)

Vector:
 [1 2 3]
Marix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [23]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("DType:",arr.dtype)


Shape: (2, 3)
Dimension: 2
Size: 6
DType: float64


### Array ReShaping

In [36]:
array = np.arange(12)
print("Original array:", array)

reshaped = array.reshape((3,4))
print("Reshape: \n",reshaped)

flattened = reshaped.flatten() #returns copy
print("\n Flattened array:", flattened)

#ravel(returns view ,instead of copy)

raveled = reshaped.ravel() #returns original array
print("\n Raveled array:", raveled)

#To get Transpose,we use .T as shown below
transpose = reshaped.T
print("Transposed array: \n",transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
