## Numpy Array operations

In [4]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing:", arr[2:7])
print("With Step:", arr[1:8:2])
print("Negative indexing:", arr[-4]) #returns last 4th value

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative indexing: 6


In [11]:
arr_2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific element:", arr_2D[1,2])
print("Entire specific Row:", arr_2D[1])
print("Entire specific Colomn:", arr_2D[:,1])

Specific element: 6
Entire specific Row: [4 5 6]
Entire specific Colomn: [2 5 8]


### Sorting

In [18]:
unsorted = np.array([1,5,2,4,3,8,7,6])
print("Sorted array:", np.sort(unsorted))

arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by coloumn: \n",np.sort(arr_2D_unsorted, axis=0))

Sorted array: [1 2 3 4 5 6 7 8]
Sorted 2D array by coloumn: 
 [[1 1]
 [2 2]
 [3 3]]


### Filter

In [19]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_numbers = numbers[numbers % 2 ==0]
print("Even numbers:",even_numbers)

Even numbers: [2 4 6 8]


### Filter with mask

In [20]:
mask = numbers>5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [6 7 8 9]


### Fancy indexing vs np.where()

In [23]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8], dtype=int64),)
NP where: [6 7 8 9]


In [25]:
condition_array = np.where(numbers > 5, "true", "false")
#if(numbers > 5){
#  true} 
#else { 
#  false }
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


### Adding and Removing data

In [26]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6 7 8]


### Array Compatibility

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,5])
print("Compatibility shape:", a.shape == b.shape)
print("Compatibility shape:", a.shape == c.shape)

Compatibility shape: True
Compatibility shape: False


In [36]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) #vstack() helps in adding a new row
print("Original is: \n",original)
print("\n")
print("With_new_row is: \n",with_new_row)

print("\n")

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new Coloumn: \n", with_new_col)

Original is: 
 [[1 2]
 [3 4]]


With_new_row is: 
 [[1 2]
 [3 4]
 [5 6]]


With new Coloumn: 
 [[1 2 7]
 [3 4 8]]


In [38]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5 6 7]
